/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Returns the health status of the application and its dependencies.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Admin Login
     * @description Authenticate an admin user and return tokens.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/mfa/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify MFA
     * @description Complete MFA step for Super Admin after successful password auth.
     */
    post: operations["mfaVerify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Logout
     * @description Terminate the current session by revoking the refresh token.
     */
    delete: operations["logout"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Access Token
     * @description Refresh the access token using a valid refresh token.
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request Password Reset
     * @description Initiate self-service password reset. Always returns success to prevent email enumeration.
     */
    post: operations["passwordResetRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm Password Reset
     * @description Reset password using token from email.
     */
    post: operations["passwordResetConfirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/accept-invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept Invite
     * @description Complete account activation using invitation token.
     */
    post: operations["acceptInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sso/initiate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Initiate SSO
     * @description Redirects the client to the Identity Provider login page.
     */
    get: operations["ssoInitiate"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sso/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSO Callback
     * @description Handle authentication response from the Identity Provider.
     */
    get: operations["ssoCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/biometric/challenge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Biometric Challenge
     * @description Generate a WebAuthn challenge for biometric authentication.
     */
    post: operations["biometricChallenge"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/biometric/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Biometric Verification
     * @description Verify WebAuthn cryptographic signature and authenticate the user.
     */
    post: operations["biometricVerify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RefreshRequest: {
      /** @example def456... */
      refresh_token: string;
    };
    HealthStatus: {
      /** @example OK */
      status?: string;
      /** @example 0.1.0 */
      version?: string;
      /** @example {
       *       "postgres": "UP",
       *       "redis": "UP",
       *       "kafka": "UP"
       *     } */
      dependencies?: {
        [key: string]: string | undefined;
      };
    };
    LoginRequest: {
      /**
       * Format: email
       * @example admin@hros.com
       */
      email: string;
      /**
       * Format: password
       * @example ********
       */
      password: string;
      /** @example true */
      remember_me?: boolean;
    };
    LoginResponse: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      access_token?: string;
      /** @example def456... */
      refresh_token?: string;
      /** @example true */
      mfa_required?: boolean;
      /** @example mfa_sess_abc123 */
      mfa_token?: string;
      /** @example [
       *       "totp",
       *       "webauthn"
       *     ] */
      mfa_methods?: string[];
    };
    MFAVerifyRequest: {
      /** @example mfa_sess_abc123 */
      mfa_token: string;
      /**
       * @example totp
       * @enum {string}
       */
      method: "totp" | "webauthn";
      /** @example 123456 */
      code?: string;
    };
    PasswordResetRequest: {
      /**
       * Format: email
       * @example admin@hros.com
       */
      email: string;
    };
    PasswordResetConfirmRequest: {
      /** @example uuid-reset-token-here */
      token: string;
      /**
       * Format: password
       * @example NewSecurePass123!
       */
      password: string;
      /**
       * Format: password
       * @example NewSecurePass123!
       */
      password_confirmation: string;
    };
    AcceptInviteRequest: {
      /** @example uuid-invite-token-here */
      token: string;
      /**
       * Format: password
       * @example NewSecurePass123!
       */
      password: string;
      /**
       * Format: password
       * @example NewSecurePass123!
       */
      password_confirmation: string;
    };
    ErrorResponse: {
      /** @example validation_error */
      code: string;
      /** @example Request validation failed */
      message: string;
      details?: {
        [key: string]: unknown;
      };
      /** @example 01HZX3QK0YS6M2Z1WD9S7VN9VJ */
      trace_id?: string;
    };
    BiometricChallengeRequest: {
      /**
       * Format: email
       * @example admin@hros.com
       */
      email: string;
    };
    BiometricChallengeResponse: {
      /** @example dGhpcyBpcyBhIGNyeXB0b2dyYXBoaWMgY2hhbGxlbmdl */
      challenge: string;
      /** @example raw_credential_id_hex_or_base64 */
      credential_id: string;
    };
    BiometricVerifyRequest: {
      /**
       * Format: email
       * @example admin@hros.com
       */
      email: string;
      /** @example raw_credential_id_hex_or_base64 */
      credential_id: string;
      /** @example raw_authenticator_data_base64 */
      authenticator_data: string;
      /** @example raw_client_data_json_base64 */
      client_data_json: string;
      /** @example raw_signature_base64 */
      signature: string;
      /** @example false */
      remember_me?: boolean;
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Not Found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Conflict */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalServerError"];
    };
  };
  mfaVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MFAVerifyRequest"];
      };
    };
    responses: {
      /** @description Verification successful, returns access/refresh tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description MFA verification failed (MFA_INVALID) or session expired (MFA_TOKEN_EXPIRED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successful */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalServerError"];
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Token refresh successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalServerError"];
    };
  };
  passwordResetRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description Password reset request accepted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example If an account exists for that email, a reset link has been sent. */
            message?: string;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      500: components["responses"]["InternalServerError"];
    };
  };
  passwordResetConfirm: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirmRequest"];
      };
    };
    responses: {
      /** @description Password updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example Password updated successfully. */
            message?: string;
          };
        };
      };
      /** @description Token expired (TOKEN_EXPIRED) or already used (TOKEN_USED) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password does not meet complexity requirements (PASSWORD_WEAK) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  acceptInvite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInviteRequest"];
      };
    };
    responses: {
      /** @description Account activated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example Account activated successfully. */
            message?: string;
          };
        };
      };
      /** @description Invite token expired (INVITE_EXPIRED) or already used (INVITE_USED) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password does not meet complexity requirements (PASSWORD_WEAK) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  ssoInitiate: {
    parameters: {
      query: {
        /** @example google */
        provider: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to Identity Provider login page */
      302: {
        headers: {
          /** @description Target URL of the Identity Provider authorization endpoint */
          Location?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      500: components["responses"]["InternalServerError"];
    };
  };
  ssoCallback: {
    parameters: {
      query: {
        /** @example auth_code_123 */
        code: string;
        /** @example state_abc */
        state: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Login successful, returns access/refresh tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid state parameter (INVALID_SSO_STATE) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description No admin account linked to this identity (NO_ACCOUNT_LINKED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  biometricChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BiometricChallengeRequest"];
      };
    };
    responses: {
      /** @description Challenge generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BiometricChallengeResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      500: components["responses"]["InternalServerError"];
    };
  };
  biometricVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BiometricVerifyRequest"];
      };
    };
    responses: {
      /** @description Authentication successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
