/**
 * Generated by openapi-typescript
 * DO NOT EDIT BY HAND.
 *
 * Placeholder: regenerate with `pnpm openapi:types` once the backend
 * `../backend/api/openapi.yaml` is available.
 */
export interface paths {}

export type webhooks = Record<string, never>;

export interface components {
  schemas: Record<string, never>;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type operations = Record<string, never>;
